#!/usr/bin/env python

"""
Copyright (c) 2013 Oleg Shparber

Permission is hereby granted, free of charge, to any person obtaining a copy of
this software and associated documentation files (the "Software"), to deal in
the Software without restriction, including without limitation the rights to
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
the Software, and to permit persons to whom the Software is furnished to do so,
subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
"""

import argparse
import json
import requests
import sys

url = "http://sandbox.paste.kde.org/api/json"

def list(page=-1):
    uri = url + "/list"
    if page != -1:
        uri += "/" + str(page)

    try:
        r = requests.get(uri)
    except Exception as e:
        print(e)
        sys.exit(1)

    try:
        result = json.loads(r.text)["result"]
    except Exception as e:
        print(e)
        sys.exit(1)

    if r.status_code == 200:
        print("Total pastes: " + str(result["count"]))
        print("Total pages: " + str(result["pages"]))
        print(result["pastes"])
    else:
        print(result["error"])
        sys.exit(1)


def show(id, hash=None, password=None):
    uri = url + "/show/" + id
    if hash != None:
        uri += "/" + hash
    if password != None:
        uri += "/" + password    

    try:
        r = requests.get(uri)
    except Exception as e:
        print(e)
        sys.exit(1)

    try:
        result = json.loads(r.text)["result"]
    except Exception as e:
        print(e)
        sys.exit(1)

    if r.status_code == 200:
        print(result["data"])
    else:
        print(result["error"])
        sys.exit(1)

def main():
    parser = argparse.ArgumentParser(description='Simple Sticky Notes Client')

    # Show a paste
    parser.add_argument("-s", "--show", help="show paste with specific id",
                        metavar="ID");
    parser.add_argument("-H", "--hash", help="hash for private paste");


    # List pastes
    parser.add_argument("-l", "--list", help="list available pastes",
                        metavar="PAGE", type=int, nargs='?',const=-1)

    # Generic arguments
    parser.add_argument("-P", "--password", help="password for protected paste");

    # TODO: remove
    if len(sys.argv) == 1:
        parser.print_help()
        sys.exit(1)

    args = parser.parse_args()

    print(args)

    if args.show != None:
        show(args.show, args.hash, args.password)
    elif args.list != None:
        list(args.list)

if __name__ == '__main__':
    main()

